package com.bocsoft.wwsf.webconsole.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bocsoft.wwsf.webconsole.example.DelayCommandExample;
import com.bocsoft.wwsf.webconsole.model.DelayCommand;

public interface DelayCommandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    long countByExample(DelayCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    int deleteByExample(DelayCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cmdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    int insert(DelayCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    int insertSelective(DelayCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    List<DelayCommand> selectByExample(DelayCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    DelayCommand selectByPrimaryKey(String cmdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DelayCommand record, @Param("example") DelayCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DelayCommand record, @Param("example") DelayCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DelayCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DelayCommand record);
}