package com.bocsoft.wwsf.webconsole.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bocsoft.wwsf.webconsole.example.InitCommandExample;
import com.bocsoft.wwsf.webconsole.model.InitCommand;

public interface InitCommandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_init
     *
     * @mbg.generated
     */
    long countByExample(InitCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_init
     *
     * @mbg.generated
     */
    int deleteByExample(InitCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_init
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cmdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_init
     *
     * @mbg.generated
     */
    int insert(InitCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_init
     *
     * @mbg.generated
     */
    int insertSelective(InitCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_init
     *
     * @mbg.generated
     */
    List<InitCommand> selectByExample(InitCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_init
     *
     * @mbg.generated
     */
    InitCommand selectByPrimaryKey(String cmdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_init
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InitCommand record, @Param("example") InitCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_init
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InitCommand record, @Param("example") InitCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_init
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InitCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_init
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InitCommand record);
}