package com.bocsoft.wwsf.webconsole.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bocsoft.wwsf.webconsole.example.MasterCommandExample;
import com.bocsoft.wwsf.webconsole.model.MasterCommand;

public interface MasterCommandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    long countByExample(MasterCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    int deleteByExample(MasterCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cmdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    int insert(MasterCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    int insertSelective(MasterCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    List<MasterCommand> selectByExampleWithBLOBs(MasterCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    List<MasterCommand> selectByExample(MasterCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    MasterCommand selectByPrimaryKey(String cmdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MasterCommand record, @Param("example") MasterCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") MasterCommand record, @Param("example") MasterCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MasterCommand record, @Param("example") MasterCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MasterCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MasterCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MasterCommand record);
}