package com.bocsoft.wwsf.webconsole.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bocsoft.wwsf.webconsole.example.SlaveCommandExample;
import com.bocsoft.wwsf.webconsole.model.SlaveCommand;

public interface SlaveCommandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv_slave
     *
     * @mbg.generated
     */
    long countByExample(SlaveCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv_slave
     *
     * @mbg.generated
     */
    int deleteByExample(SlaveCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv_slave
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String cmdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv_slave
     *
     * @mbg.generated
     */
    int insert(SlaveCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv_slave
     *
     * @mbg.generated
     */
    int insertSelective(SlaveCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv_slave
     *
     * @mbg.generated
     */
    List<SlaveCommand> selectByExample(SlaveCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv_slave
     *
     * @mbg.generated
     */
    SlaveCommand selectByPrimaryKey(String cmdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv_slave
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SlaveCommand record, @Param("example") SlaveCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv_slave
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SlaveCommand record, @Param("example") SlaveCommandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv_slave
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SlaveCommand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv_slave
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SlaveCommand record);
}