package com.bocsoft.wwsf.webconsole.model;

public class MasterCommand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ww_queue_rcv.cmd_id
     *
     * @mbg.generated
     */
    private String cmdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ww_queue_rcv.product
     *
     * @mbg.generated
     */
    private String product;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ww_queue_rcv.cmd_mold
     *
     * @mbg.generated
     */
    private String cmdMold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ww_queue_rcv.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ww_queue_rcv.batch
     *
     * @mbg.generated
     */
    private String batch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ww_queue_rcv.job_ins_id
     *
     * @mbg.generated
     */
    private Long jobInsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ww_queue_rcv.occu_time
     *
     * @mbg.generated
     */
    private Long occuTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ww_queue_rcv.cmd_content
     *
     * @mbg.generated
     */
    private String cmdContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    public MasterCommand(String cmdId, String product, String cmdMold, String state, String batch, Long jobInsId, Long occuTime) {
        this.cmdId = cmdId;
        this.product = product;
        this.cmdMold = cmdMold;
        this.state = state;
        this.batch = batch;
        this.jobInsId = jobInsId;
        this.occuTime = occuTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    public MasterCommand(String cmdId, String product, String cmdMold, String state, String batch, Long jobInsId, Long occuTime, String cmdContent) {
        this.cmdId = cmdId;
        this.product = product;
        this.cmdMold = cmdMold;
        this.state = state;
        this.batch = batch;
        this.jobInsId = jobInsId;
        this.occuTime = occuTime;
        this.cmdContent = cmdContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_rcv
     *
     * @mbg.generated
     */
    public MasterCommand() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ww_queue_rcv.cmd_id
     *
     * @return the value of ww_queue_rcv.cmd_id
     *
     * @mbg.generated
     */
    public String getCmdId() {
        return cmdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ww_queue_rcv.cmd_id
     *
     * @param cmdId the value for ww_queue_rcv.cmd_id
     *
     * @mbg.generated
     */
    public void setCmdId(String cmdId) {
        this.cmdId = cmdId == null ? null : cmdId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ww_queue_rcv.product
     *
     * @return the value of ww_queue_rcv.product
     *
     * @mbg.generated
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ww_queue_rcv.product
     *
     * @param product the value for ww_queue_rcv.product
     *
     * @mbg.generated
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ww_queue_rcv.cmd_mold
     *
     * @return the value of ww_queue_rcv.cmd_mold
     *
     * @mbg.generated
     */
    public String getCmdMold() {
        return cmdMold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ww_queue_rcv.cmd_mold
     *
     * @param cmdMold the value for ww_queue_rcv.cmd_mold
     *
     * @mbg.generated
     */
    public void setCmdMold(String cmdMold) {
        this.cmdMold = cmdMold == null ? null : cmdMold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ww_queue_rcv.state
     *
     * @return the value of ww_queue_rcv.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ww_queue_rcv.state
     *
     * @param state the value for ww_queue_rcv.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ww_queue_rcv.batch
     *
     * @return the value of ww_queue_rcv.batch
     *
     * @mbg.generated
     */
    public String getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ww_queue_rcv.batch
     *
     * @param batch the value for ww_queue_rcv.batch
     *
     * @mbg.generated
     */
    public void setBatch(String batch) {
        this.batch = batch == null ? null : batch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ww_queue_rcv.job_ins_id
     *
     * @return the value of ww_queue_rcv.job_ins_id
     *
     * @mbg.generated
     */
    public Long getJobInsId() {
        return jobInsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ww_queue_rcv.job_ins_id
     *
     * @param jobInsId the value for ww_queue_rcv.job_ins_id
     *
     * @mbg.generated
     */
    public void setJobInsId(Long jobInsId) {
        this.jobInsId = jobInsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ww_queue_rcv.occu_time
     *
     * @return the value of ww_queue_rcv.occu_time
     *
     * @mbg.generated
     */
    public Long getOccuTime() {
        return occuTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ww_queue_rcv.occu_time
     *
     * @param occuTime the value for ww_queue_rcv.occu_time
     *
     * @mbg.generated
     */
    public void setOccuTime(Long occuTime) {
        this.occuTime = occuTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ww_queue_rcv.cmd_content
     *
     * @return the value of ww_queue_rcv.cmd_content
     *
     * @mbg.generated
     */
    public String getCmdContent() {
        return cmdContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ww_queue_rcv.cmd_content
     *
     * @param cmdContent the value for ww_queue_rcv.cmd_content
     *
     * @mbg.generated
     */
    public void setCmdContent(String cmdContent) {
        this.cmdContent = cmdContent == null ? null : cmdContent.trim();
    }
}