package com.bocsoft.wwsf.webconsole.example;

import java.util.ArrayList;
import java.util.List;

public class DelayCommandExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    public DelayCommandExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCmdIdIsNull() {
            addCriterion("cmd_id is null");
            return (Criteria) this;
        }

        public Criteria andCmdIdIsNotNull() {
            addCriterion("cmd_id is not null");
            return (Criteria) this;
        }

        public Criteria andCmdIdEqualTo(String value) {
            addCriterion("cmd_id =", value, "cmdId");
            return (Criteria) this;
        }

        public Criteria andCmdIdNotEqualTo(String value) {
            addCriterion("cmd_id <>", value, "cmdId");
            return (Criteria) this;
        }

        public Criteria andCmdIdGreaterThan(String value) {
            addCriterion("cmd_id >", value, "cmdId");
            return (Criteria) this;
        }

        public Criteria andCmdIdGreaterThanOrEqualTo(String value) {
            addCriterion("cmd_id >=", value, "cmdId");
            return (Criteria) this;
        }

        public Criteria andCmdIdLessThan(String value) {
            addCriterion("cmd_id <", value, "cmdId");
            return (Criteria) this;
        }

        public Criteria andCmdIdLessThanOrEqualTo(String value) {
            addCriterion("cmd_id <=", value, "cmdId");
            return (Criteria) this;
        }

        public Criteria andCmdIdLike(String value) {
            addCriterion("cmd_id like", value, "cmdId");
            return (Criteria) this;
        }

        public Criteria andCmdIdNotLike(String value) {
            addCriterion("cmd_id not like", value, "cmdId");
            return (Criteria) this;
        }

        public Criteria andCmdIdIn(List<String> values) {
            addCriterion("cmd_id in", values, "cmdId");
            return (Criteria) this;
        }

        public Criteria andCmdIdNotIn(List<String> values) {
            addCriterion("cmd_id not in", values, "cmdId");
            return (Criteria) this;
        }

        public Criteria andCmdIdBetween(String value1, String value2) {
            addCriterion("cmd_id between", value1, value2, "cmdId");
            return (Criteria) this;
        }

        public Criteria andCmdIdNotBetween(String value1, String value2) {
            addCriterion("cmd_id not between", value1, value2, "cmdId");
            return (Criteria) this;
        }

        public Criteria andProductIsNull() {
            addCriterion("product is null");
            return (Criteria) this;
        }

        public Criteria andProductIsNotNull() {
            addCriterion("product is not null");
            return (Criteria) this;
        }

        public Criteria andProductEqualTo(String value) {
            addCriterion("product =", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductNotEqualTo(String value) {
            addCriterion("product <>", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductGreaterThan(String value) {
            addCriterion("product >", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductGreaterThanOrEqualTo(String value) {
            addCriterion("product >=", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductLessThan(String value) {
            addCriterion("product <", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductLessThanOrEqualTo(String value) {
            addCriterion("product <=", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductLike(String value) {
            addCriterion("product like", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductNotLike(String value) {
            addCriterion("product not like", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductIn(List<String> values) {
            addCriterion("product in", values, "product");
            return (Criteria) this;
        }

        public Criteria andProductNotIn(List<String> values) {
            addCriterion("product not in", values, "product");
            return (Criteria) this;
        }

        public Criteria andProductBetween(String value1, String value2) {
            addCriterion("product between", value1, value2, "product");
            return (Criteria) this;
        }

        public Criteria andProductNotBetween(String value1, String value2) {
            addCriterion("product not between", value1, value2, "product");
            return (Criteria) this;
        }

        public Criteria andAgentIsNull() {
            addCriterion("agent is null");
            return (Criteria) this;
        }

        public Criteria andAgentIsNotNull() {
            addCriterion("agent is not null");
            return (Criteria) this;
        }

        public Criteria andAgentEqualTo(String value) {
            addCriterion("agent =", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotEqualTo(String value) {
            addCriterion("agent <>", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentGreaterThan(String value) {
            addCriterion("agent >", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentGreaterThanOrEqualTo(String value) {
            addCriterion("agent >=", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLessThan(String value) {
            addCriterion("agent <", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLessThanOrEqualTo(String value) {
            addCriterion("agent <=", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLike(String value) {
            addCriterion("agent like", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotLike(String value) {
            addCriterion("agent not like", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentIn(List<String> values) {
            addCriterion("agent in", values, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotIn(List<String> values) {
            addCriterion("agent not in", values, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentBetween(String value1, String value2) {
            addCriterion("agent between", value1, value2, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotBetween(String value1, String value2) {
            addCriterion("agent not between", value1, value2, "agent");
            return (Criteria) this;
        }

        public Criteria andCmdMoldIsNull() {
            addCriterion("cmd_mold is null");
            return (Criteria) this;
        }

        public Criteria andCmdMoldIsNotNull() {
            addCriterion("cmd_mold is not null");
            return (Criteria) this;
        }

        public Criteria andCmdMoldEqualTo(String value) {
            addCriterion("cmd_mold =", value, "cmdMold");
            return (Criteria) this;
        }

        public Criteria andCmdMoldNotEqualTo(String value) {
            addCriterion("cmd_mold <>", value, "cmdMold");
            return (Criteria) this;
        }

        public Criteria andCmdMoldGreaterThan(String value) {
            addCriterion("cmd_mold >", value, "cmdMold");
            return (Criteria) this;
        }

        public Criteria andCmdMoldGreaterThanOrEqualTo(String value) {
            addCriterion("cmd_mold >=", value, "cmdMold");
            return (Criteria) this;
        }

        public Criteria andCmdMoldLessThan(String value) {
            addCriterion("cmd_mold <", value, "cmdMold");
            return (Criteria) this;
        }

        public Criteria andCmdMoldLessThanOrEqualTo(String value) {
            addCriterion("cmd_mold <=", value, "cmdMold");
            return (Criteria) this;
        }

        public Criteria andCmdMoldLike(String value) {
            addCriterion("cmd_mold like", value, "cmdMold");
            return (Criteria) this;
        }

        public Criteria andCmdMoldNotLike(String value) {
            addCriterion("cmd_mold not like", value, "cmdMold");
            return (Criteria) this;
        }

        public Criteria andCmdMoldIn(List<String> values) {
            addCriterion("cmd_mold in", values, "cmdMold");
            return (Criteria) this;
        }

        public Criteria andCmdMoldNotIn(List<String> values) {
            addCriterion("cmd_mold not in", values, "cmdMold");
            return (Criteria) this;
        }

        public Criteria andCmdMoldBetween(String value1, String value2) {
            addCriterion("cmd_mold between", value1, value2, "cmdMold");
            return (Criteria) this;
        }

        public Criteria andCmdMoldNotBetween(String value1, String value2) {
            addCriterion("cmd_mold not between", value1, value2, "cmdMold");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andBatchIsNull() {
            addCriterion("batch is null");
            return (Criteria) this;
        }

        public Criteria andBatchIsNotNull() {
            addCriterion("batch is not null");
            return (Criteria) this;
        }

        public Criteria andBatchEqualTo(String value) {
            addCriterion("batch =", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotEqualTo(String value) {
            addCriterion("batch <>", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchGreaterThan(String value) {
            addCriterion("batch >", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchGreaterThanOrEqualTo(String value) {
            addCriterion("batch >=", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLessThan(String value) {
            addCriterion("batch <", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLessThanOrEqualTo(String value) {
            addCriterion("batch <=", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLike(String value) {
            addCriterion("batch like", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotLike(String value) {
            addCriterion("batch not like", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchIn(List<String> values) {
            addCriterion("batch in", values, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotIn(List<String> values) {
            addCriterion("batch not in", values, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchBetween(String value1, String value2) {
            addCriterion("batch between", value1, value2, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotBetween(String value1, String value2) {
            addCriterion("batch not between", value1, value2, "batch");
            return (Criteria) this;
        }

        public Criteria andJobInsIdIsNull() {
            addCriterion("job_ins_id is null");
            return (Criteria) this;
        }

        public Criteria andJobInsIdIsNotNull() {
            addCriterion("job_ins_id is not null");
            return (Criteria) this;
        }

        public Criteria andJobInsIdEqualTo(Long value) {
            addCriterion("job_ins_id =", value, "jobInsId");
            return (Criteria) this;
        }

        public Criteria andJobInsIdNotEqualTo(Long value) {
            addCriterion("job_ins_id <>", value, "jobInsId");
            return (Criteria) this;
        }

        public Criteria andJobInsIdGreaterThan(Long value) {
            addCriterion("job_ins_id >", value, "jobInsId");
            return (Criteria) this;
        }

        public Criteria andJobInsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("job_ins_id >=", value, "jobInsId");
            return (Criteria) this;
        }

        public Criteria andJobInsIdLessThan(Long value) {
            addCriterion("job_ins_id <", value, "jobInsId");
            return (Criteria) this;
        }

        public Criteria andJobInsIdLessThanOrEqualTo(Long value) {
            addCriterion("job_ins_id <=", value, "jobInsId");
            return (Criteria) this;
        }

        public Criteria andJobInsIdIn(List<Long> values) {
            addCriterion("job_ins_id in", values, "jobInsId");
            return (Criteria) this;
        }

        public Criteria andJobInsIdNotIn(List<Long> values) {
            addCriterion("job_ins_id not in", values, "jobInsId");
            return (Criteria) this;
        }

        public Criteria andJobInsIdBetween(Long value1, Long value2) {
            addCriterion("job_ins_id between", value1, value2, "jobInsId");
            return (Criteria) this;
        }

        public Criteria andJobInsIdNotBetween(Long value1, Long value2) {
            addCriterion("job_ins_id not between", value1, value2, "jobInsId");
            return (Criteria) this;
        }

        public Criteria andCmdContentIsNull() {
            addCriterion("cmd_content is null");
            return (Criteria) this;
        }

        public Criteria andCmdContentIsNotNull() {
            addCriterion("cmd_content is not null");
            return (Criteria) this;
        }

        public Criteria andCmdContentEqualTo(String value) {
            addCriterion("cmd_content =", value, "cmdContent");
            return (Criteria) this;
        }

        public Criteria andCmdContentNotEqualTo(String value) {
            addCriterion("cmd_content <>", value, "cmdContent");
            return (Criteria) this;
        }

        public Criteria andCmdContentGreaterThan(String value) {
            addCriterion("cmd_content >", value, "cmdContent");
            return (Criteria) this;
        }

        public Criteria andCmdContentGreaterThanOrEqualTo(String value) {
            addCriterion("cmd_content >=", value, "cmdContent");
            return (Criteria) this;
        }

        public Criteria andCmdContentLessThan(String value) {
            addCriterion("cmd_content <", value, "cmdContent");
            return (Criteria) this;
        }

        public Criteria andCmdContentLessThanOrEqualTo(String value) {
            addCriterion("cmd_content <=", value, "cmdContent");
            return (Criteria) this;
        }

        public Criteria andCmdContentLike(String value) {
            addCriterion("cmd_content like", value, "cmdContent");
            return (Criteria) this;
        }

        public Criteria andCmdContentNotLike(String value) {
            addCriterion("cmd_content not like", value, "cmdContent");
            return (Criteria) this;
        }

        public Criteria andCmdContentIn(List<String> values) {
            addCriterion("cmd_content in", values, "cmdContent");
            return (Criteria) this;
        }

        public Criteria andCmdContentNotIn(List<String> values) {
            addCriterion("cmd_content not in", values, "cmdContent");
            return (Criteria) this;
        }

        public Criteria andCmdContentBetween(String value1, String value2) {
            addCriterion("cmd_content between", value1, value2, "cmdContent");
            return (Criteria) this;
        }

        public Criteria andCmdContentNotBetween(String value1, String value2) {
            addCriterion("cmd_content not between", value1, value2, "cmdContent");
            return (Criteria) this;
        }

        public Criteria andOccuTimeIsNull() {
            addCriterion("occu_time is null");
            return (Criteria) this;
        }

        public Criteria andOccuTimeIsNotNull() {
            addCriterion("occu_time is not null");
            return (Criteria) this;
        }

        public Criteria andOccuTimeEqualTo(Long value) {
            addCriterion("occu_time =", value, "occuTime");
            return (Criteria) this;
        }

        public Criteria andOccuTimeNotEqualTo(Long value) {
            addCriterion("occu_time <>", value, "occuTime");
            return (Criteria) this;
        }

        public Criteria andOccuTimeGreaterThan(Long value) {
            addCriterion("occu_time >", value, "occuTime");
            return (Criteria) this;
        }

        public Criteria andOccuTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("occu_time >=", value, "occuTime");
            return (Criteria) this;
        }

        public Criteria andOccuTimeLessThan(Long value) {
            addCriterion("occu_time <", value, "occuTime");
            return (Criteria) this;
        }

        public Criteria andOccuTimeLessThanOrEqualTo(Long value) {
            addCriterion("occu_time <=", value, "occuTime");
            return (Criteria) this;
        }

        public Criteria andOccuTimeIn(List<Long> values) {
            addCriterion("occu_time in", values, "occuTime");
            return (Criteria) this;
        }

        public Criteria andOccuTimeNotIn(List<Long> values) {
            addCriterion("occu_time not in", values, "occuTime");
            return (Criteria) this;
        }

        public Criteria andOccuTimeBetween(Long value1, Long value2) {
            addCriterion("occu_time between", value1, value2, "occuTime");
            return (Criteria) this;
        }

        public Criteria andOccuTimeNotBetween(Long value1, Long value2) {
            addCriterion("occu_time not between", value1, value2, "occuTime");
            return (Criteria) this;
        }

        public Criteria andExeTimeIsNull() {
            addCriterion("exe_time is null");
            return (Criteria) this;
        }

        public Criteria andExeTimeIsNotNull() {
            addCriterion("exe_time is not null");
            return (Criteria) this;
        }

        public Criteria andExeTimeEqualTo(Long value) {
            addCriterion("exe_time =", value, "exeTime");
            return (Criteria) this;
        }

        public Criteria andExeTimeNotEqualTo(Long value) {
            addCriterion("exe_time <>", value, "exeTime");
            return (Criteria) this;
        }

        public Criteria andExeTimeGreaterThan(Long value) {
            addCriterion("exe_time >", value, "exeTime");
            return (Criteria) this;
        }

        public Criteria andExeTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("exe_time >=", value, "exeTime");
            return (Criteria) this;
        }

        public Criteria andExeTimeLessThan(Long value) {
            addCriterion("exe_time <", value, "exeTime");
            return (Criteria) this;
        }

        public Criteria andExeTimeLessThanOrEqualTo(Long value) {
            addCriterion("exe_time <=", value, "exeTime");
            return (Criteria) this;
        }

        public Criteria andExeTimeIn(List<Long> values) {
            addCriterion("exe_time in", values, "exeTime");
            return (Criteria) this;
        }

        public Criteria andExeTimeNotIn(List<Long> values) {
            addCriterion("exe_time not in", values, "exeTime");
            return (Criteria) this;
        }

        public Criteria andExeTimeBetween(Long value1, Long value2) {
            addCriterion("exe_time between", value1, value2, "exeTime");
            return (Criteria) this;
        }

        public Criteria andExeTimeNotBetween(Long value1, Long value2) {
            addCriterion("exe_time not between", value1, value2, "exeTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ww_queue_delay
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ww_queue_delay
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}